ci(node-setup-and-dependencies): add validation

diff --git a/composite/node-setup-and-dependencies/action.yml b/composite/node-setup-and-dependencies/action.yml
--- a/composite/node-setup-and-dependencies/action.yml
+++ b/composite/node-setup-and-dependencies/action.yml
@@ -117,6 +117,33 @@ runs:
       with:
         workflow-inputs: ${{ toJson(inputs) }}
 
+    - name: Validation
+      run: |
+        set -xeu
+
+        #  Validate npm registry URL
+        if [[ "${{ inputs.npm-registry-url }}" ]]; then
+          if ! [[ "${{ inputs.npm-registry-url }}" =~ ^https://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[a-zA-Z0-9.-]*)*$ ]]; then
+            echo "Error: Invalid npm registry URL provided. Please ensure the URL starts with 'https://' and follows a valid domain format, e.g., 'https://registry.npmjs.org'."
+            exit 1
+          fi
+        fi
+
+        # Validate npm scope
+        if [[ "${{ inputs.npm-scope }}" ]]; then
+          if ! [[ "${{ inputs.npm-scope }}" =~ ^@[a-zA-Z0-9.-]+$ ]]; then
+            echo "Error: Invalid npm scope provided. The scope must start with '@' followed by alphanumeric characters, e.g., '@myorg'."
+            exit 1
+          fi
+        fi
+
+        # Validate npm install command
+        if [[ "${{ inputs.npm-install-command }}" != "ci" && "${{ inputs.npm-install-command }}" != "install" ]]; then
+          echo "Error: Invalid npm install command provided."
+          exit 1
+        fi
+      shell: bash
+
     - name: Checkout code
       if: ${{ inputs.skip-checkout == 'false' }}
       uses: actions/checkout@v4
