refactor: refactor error output

diff --git a/composite/setup-environment-variables/action.yml b/composite/setup-environment-variables/action.yml
--- a/composite/setup-environment-variables/action.yml
+++ b/composite/setup-environment-variables/action.yml
@@ -52,8 +52,8 @@ runs:
             echo "Setting: $key=$value"
             echo "$key=$value" >> "$GITHUB_ENV"
           else
-            echo "Error: Invalid key format '$key'" >&2
-            exit 1  # 不正なキーが検出された場合はエラーで終了
+            echo "::error::Invalid key format '$key'" >&2
+            exit 1 # 不正なキーが検出された場合はエラーで終了
           fi
         done
       shell: bash
