ci(setup-enviironment-variables): 入力値のチェック強化とエラーハンドリングの追加

diff --git a/composite/setup-environment-variables/action.yml b/composite/setup-environment-variables/action.yml
--- a/composite/setup-environment-variables/action.yml
+++ b/composite/setup-environment-variables/action.yml
@@ -35,8 +35,7 @@ runs:
     - name: Validate and Set Environment Variables
       if: ${{ inputs.environment-variables != '' }}
       run: |
-        set -x
-        set -e
+        set -xeu
 
         # 入力値をシングルクォーテーションで囲むことで、文字列がそのまま保持されるようにする。
         # GitHub Actionsの式展開を避けて、入力された文字列がスクリプト内で正確に解析されるようにするため。
@@ -44,7 +43,7 @@ runs:
         echo "$env_vars"
 
         # 正規表現を使ってキーと値を抽出
-        echo "$env_vars" | grep -oP '(?:\w+="[^"]+")' | while IFS='=' read -r key value; do
+        echo "$env_vars" | grep -oP '(?:\w+="(?:[^"\\]|\\.)*")' | while IFS='=' read -r key value; do
           # キーが環境変数として適切かチェック
           if [[ "$key" =~ ^[A-Za-z_][A-Za-z_0-9]*$ ]]; then
             # 値から引用符を削除
@@ -53,7 +52,8 @@ runs:
             echo "Setting: $key=$value"
             echo "$key=$value" >> "$GITHUB_ENV"
           else
-            echo "Error: Invalid key format '$key'"
+            echo "Error: Invalid key format '$key'" >&2
+            exit 1  # 不正なキーが検出された場合はエラーで終了
           fi
         done
       shell: bash
